version: '3.8'
services:
  database:
    container_name: 'postgres'
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
volumes:
  postgres_data:
    driver: local